fix: run dart fix
witnet/witnet_wallet pull request #65
Opened 2023-04-12 16:49 UTC by Tommytrg

2023-04-12 22:53 UTC, parodyBit commented
Happy to see this!
The repo has gone through several dart/flutter updates and updating the depreciated items clears some of the warning logs 🔥

2023-04-13 00:35 UTC, parodyBit approved these changes

2023-04-13 02:23 UTC, parodyBit commented
the `name` property of an `enum` is only available since SDK 2.15.0-
so we should roll file `pubspec.yaml`
```
environment:
  sdk: ">=2.14.0 <3.0.0"
```
to 
```
  sdk: ">=2.15.0 <3.0.0"
```

2023-04-13 09:03 UTC, gabaldon requested changes
The color of the paddedButton in the dark mode is incorrect:

Incorrect:
![Screenshot 2023-04-13 at 10 56 23](https://user-images.githubusercontent.com/16032491/231709580-cda2078a-bdfd-48e3-b807-ea6ac97a4684.png)
Correct:
![Screenshot 2023-04-13 at 11 00 04](https://user-images.githubusercontent.com/16032491/231709763-c35b7a8c-c9dc-4fb0-b602-b5b67b302c84.png)

The commit where the ListView padding is deleted is missing:
Incorrect:
![Screenshot 2023-04-13 at 10 56 32](https://user-images.githubusercontent.com/16032491/231709583-e703e3c5-4c9c-4541-a46e-5876987aa5f0.png)
Correct:
![Screenshot 2023-04-13 at 10 59 49](https://user-images.githubusercontent.com/16032491/231710183-237cb4cb-6cf4-4076-8331-13947ec5fb81.png)

2023-04-13 14:16 UTC, gabaldon reviewed
One last change:
Incorrect:
![Screenshot 2023-04-13 at 16 11 18](https://user-images.githubusercontent.com/16032491/231786142-6a0378d5-003d-468c-b3d7-27de53c5cfd8.png)
Correct:
![Screenshot 2023-04-13 at 16 15 26](https://user-images.githubusercontent.com/16032491/231787206-2365b23c-bea7-4adc-a4f2-0715d08a51f5.png)

2023-04-13 16:07 UTC, gabaldon requested changes

2023-04-13 16:07 UTC, gabaldon commented on lib/widgets/PaddedButton.dart
> +      style: theme.elevatedButtonTheme.style?.merge(ElevatedButton.styleFrom(
instead add this to the light and dark theme
    `ElevatedButton.styleFrom(
        foregroundColor: Colors.white, // changes the color of the text`

2023-04-14 10:03 UTC, gabaldon approved these changes

2023-04-14 10:33 UTC, merged